### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by jkd820** [branislavhesko/segmentation_framework#2]
Are there any requirements for the input data format?  Can be nii.gz or dcm ?

**Comment by jkd820** [comment]
Looking forward to your suggestions, thanks.

**Comment by branislavhesko** [comment]
Currently, the support is limited to opencv compatible formats: png, jpg, bmp, tif ... In a few days I will start on refactoring and improvements. This will be reflected in enhancements in the README.md, which will contain further information about supported formats.

**Comment by jkd820** [comment]
Thank you for your reply! I get it.
